# Generated by Django 5.2 on 2025-06-06 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('produto', '0002_remove_produto_estoqueatual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={},
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='movimento',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='nf',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='tp',
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EstoqueItem',
        ),
    ]
