# Generated by Django 5.2 on 2025-05-15 17:21

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0005_rename_preco_produto_valorpago_produto_valorvenda'),
        ('tipoDePagamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
            ],
            options={
                'db_table': 'ItemVenda',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaFiscal', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='O código de barras deve conter apenas números.', regex='^\\d+$')])),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tipoDePagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoDePagamento.tipodepagamento')),
            ],
            options={
                'db_table': 'Venda',
            },
        ),
    ]
