# Generated by Django 5.2 on 2025-06-06 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('produto', '0002_remove_produto_estoqueatual_and_more'),
        ('tipoDePagamento', '0003_rename_nome_tipodepagamento_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('tipoDePagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoDePagamento.tipodepagamento')),
            ],
            options={
                'db_table': 'Venda',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.BigIntegerField()),
                ('preco', models.FloatField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
            options={
                'db_table': 'ItemVenda',
            },
        ),
    ]
