# Generated by Django 5.2 on 2025-05-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='venda.venda'),
            preserve_default=False,
        ),
    ]
