# Generated by Django 5.2 on 2025-05-16 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='O código de barras deve conter apenas números.', regex='^\\d+$')]),
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='Fornecedor',
        ),
    ]
