# Generated by Django 5.2 on 2025-06-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=12)),
                ('cpe', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
    ]
