# Generated by Django 5.2 on 2025-06-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoDePagamento', '0002_alter_tipodepagamento_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodepagamento',
            old_name='nome',
            new_name='tipo',
        ),
        migrations.AlterModelTable(
            name='tipodepagamento',
            table='TipoDePagamento',
        ),
    ]
