# Generated by Django 5.2 on 2025-05-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0007_remove_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
            ],
            options={
                'db_table': 'Extoque',
            },
        ),
    ]
