# Generated by Django 5.2 on 2025-05-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_alter_categoria_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importado', models.BooleanField(default=False)),
                ('ncm', models.CharField(max_length=8)),
                ('nome', models.CharField(max_length=50)),
                ('estoqueAtual', models.IntegerField()),
                ('estoqueMinimo', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
            ],
            options={
                'db_table': 'Produto',
                'ordering': ('nome',),
            },
        ),
    ]
