# Generated by Django 5.2 on 2025-06-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoqueAtual',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoqueMinimo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
