# Generated by Django 5.2 on 2025-05-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='Produto',
        ),
    ]
