# Generated by Django 5.2 on 2025-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(max_length=20),
        ),
    ]
