# Generated by Django 5.2 on 2025-05-13 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_cod_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O código de barras deve conter apenas números.', regex='^\\d+$')]),
        ),
    ]
