# Generated by Django 5.2 on 2025-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_cod_barras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='valorPago',
        ),
        migrations.AddField(
            model_name='produto',
            name='valorVenda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
            preserve_default=False,
        ),
    ]
