# Generated by Django 5.2 on 2025-05-15 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_rename_preco_produto_valorpago_produto_valorvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O código de barras deve conter apenas números.', regex='^\\d+$')]),
        ),
    ]
