# Generated by Django 5.2 on 2025-05-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_cod_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
