# Generated by Django 5.2 on 2025-05-15 16:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('tipoDePagamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('notaFiscal', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='O código de barras deve conter apenas números.', regex='^\\d+$')])),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedor.fornecedor')),
                ('tipoDePagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoDePagamento.tipodepagamento')),
            ],
            options={
                'db_table': 'Compra',
            },
        ),
    ]
