# Generated by Django 5.2 on 2025-05-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
        ('produto', '0005_rename_preco_produto_valorpago_produto_valorvenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nome',
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
            ],
            options={
                'db_table': 'ItemCompra',
            },
        ),
    ]
