# Generated by Django 5.2 on 2025-05-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_remove_compra_nome_itemcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='compra.compra'),
            preserve_default=False,
        ),
    ]
