# Generated by Django 5.2 on 2025-06-06 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notaFiscal', '0001_initial'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda'),
        ),
    ]
